version: 2.1

jobs:
  setup-terragrunt:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run:
          name: Install Brew
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)";
      - run:
          name: Install Terragrunt
          command: |
            echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/circleci/.profile;
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)";
            sudo apt-get install build-essential;
            brew doctor;
            brew install terragrunt;
workflows:
  build:
    jobs:
      - setup-terragrunt:
          name: Setup Terragrunt